version: '3.9'

volumes:
  grafana_data: {}

networks:
  back-tier:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PREDICTIONS_OUTPUT_STREAM=${PREDICTIONS_OUTPUT_STREAM}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      # DB vars
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # AWS vars
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    networks:
      - back-tier

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
    networks:
      - back-tier

  grafana:
      image: grafana/grafana
      user: "472"
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - 3000:3000
      networks:
        - back-tier
      volumes:
        - ./model_monitoring/config/grafana_datasourcers.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
        - ./model_monitoring/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
        - ./model_monitoring/dashboards:/opt/grafana/dashboards
