version: '3.9'

volumes:
  grafana_data: {}

networks:
  back-tier:
  front-tier:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PREDICTIONS_OUTPUT_STREAM=${PREDICTIONS_OUTPUT_STREAM}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypass123
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    networks:
      - back-tier
      - front-tier

  grafana:
      image: grafana/grafana
      user: "472"
      restart: always
      ports:
        - 3000:3000
      networks:
        - back-tier
        - front-tier
      volumes:
        - ./model_monitoring/config/grafana_datasourcers.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
        - ./model_monitoring/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
        - ./model_monitoring/dashboards:/opt/grafana/dashboards
