{
 "title": "evidently_metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Drift",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT drift_detected FROM evidently_metrics ORDER BY timezone DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Data Drift",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT column_drift_metric FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Historical data",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 5, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \"GDP\", \"Inflation rate\", \"Tuition fees up to date\", \"Scholarship holder\", \"Curricular units 1st sem (approved)\", \"Curricular units 1st sem (enrolled)\", \"Curricular units 2nd sem (approved)\", prediction, timezone FROM historical_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT current_share_of_missing_values, reference_share_of_missing_values FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_drifted_columns FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}