DATA:
  RAW:
    ORIGIN: https://archive-beta.ics.uci.edu/static/public/697/predict+students+dropout+and+academic+success.zip
    TARGET_PATH: ./data/raw
  PREPROCESSED: ./data/preprocessed

MLFLOW_PORT: 5000

FEATURES:
  NUMERICAL:
  - GDP
  - Inflation rate
  CATEGORICAL:
  - Tuition fees up to date
  - Scholarship holder
  - Curricular units 1st sem (approved)
  - Curricular units 1st sem (enrolled)
  - Curricular units 2nd sem (approved)

TARGET: Target

MLFLOW:
  PORT: 5000
  MODEL_NAME: student-dropout-classifier
  EXPERIMENTS:
    OPTIMIZED_MODELS: optimized-student-dropout-models
    BEST_MODEL: student-dropout-best-model
    MODEL_EXPERIMENTS: student-dropout-models

PREFECT_DEPLOYMENT_NAME: 'Model training'
