name: Student Dropout Classifier - Continuous Delivery Pipeline
on:
  workflow_run:
    workflows: ['continuous-integration']
    types:
    - completed

  pull_request:
    branches:
    - 'master'
    paths:
    - 'streaming/**'

jobs:

  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing dependences
      run: |
        pip install --upgrade pip
        pip install --user pipenv && pipenv install --dev
