name: Student Dropout Classifier - Continuous Training Pipeline
on:
  pull_request:
    branches:
    - 'master'

jobs:

  continuous-training:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing dependences
      run: |
        pip install --upgrade pip
        pip install --user pipenv && pipenv install --dev
