name: Student Dropout Classifier - Continuous Integration Pipeline
on:
  pull_request:
    branches:
    - 'master'
    paths:
    - 'config/**'
    - 'streaming/**'

jobs:

  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing dependences
      run: |
        pip install --upgrade pip
        pip install --user pipenv && pipenv install --dev

    - name: Run Unit tests
      env:
        PYTHONPATH: .
      run: pipenv run pytest streaming/tests/

    - name: Lint
      run: pipenv run pylint --recursive=y .

    - name: Integration Test
      working-directory: 'streaming/integration-tests'
      env:
        AWS_ACCESS_KEY_ID: 123
        AWS_SECRET_ACCESS_KEY: 123
        AWS_DEFAULT_REGION: us-east-2
      run: |
        . run.sh
