name: Student Dropout classifier - CI Pipeline
on:
  pull_request:
    branches:
    - 'master'
    paths:
    - 'streaming/**'

jobs:

  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing dependences
      run: |
        pip install --upgrade pip
        pip install --user pipenv && pipenv install --dev

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${ env.AWS_ACCESS_KEY_ID }
        aws-secret-access-key: ${ env.AWS_SECRET_ACCESS_KEY }
        aws-region: 'us-east-2'

    - name: Run quality checks, unit and integration tests
      run: make integration_test
